title: Jordy Salvatierra Peñafiel 
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Inicio
    url: /index.html
  - title: Acerca de mí
    url: /about
  - title: Contacto
    url: /contact

social:
  github: JordySP
  twitter: Jordy_Javier123
  facebook: Jordy Javier Salvatierra Peñafiel 
  email: jordyjavier100@gmail.com

google_analytics: "UA-58263416-1"
